version: "3.9"
services:
  experimental_workout_bot:
    image: alexeynchernyshov/workout_bot:latest
    container_name: experimental
    volumes:
      - ./experimental/secrets:/app/secrets
    deploy:
      restart_policy:
        condition: on-failure
